-- NOS CONECTAMOS A LA BD POSTGRES CON EL USUARIO POSTGRES.
CREATE DATABASE bd_campus;
CREATE USER testeador WITH PASSWORD '123456';
CREATE ROLE analitico;
GRANT ALL PRIVILEGES ON DATABASE "bd_campus" TO analitico;

-- NOS CONECTAMOS A LA BD_CAMPUS, AUN CON EL USUARIO POSTGRES.
GRANT ALL ON SCHEMA public TO analitico;
GRANT analitico TO testeador;

-- NOS CONECTAMOS A BD_CAMPUS CON EL USUARIO TESTEADOR.
-- ELIMINAMOS LAS TABLAS SI ES QUE EXISTEN.
DROP TABLE IF EXISTS "cancha" CASCADE;
DROP TABLE IF EXISTS "categoria" CASCADE;
DROP TABLE IF EXISTS "comuna" CASCADE;
DROP TABLE IF EXISTS "equipo" CASCADE;
DROP TABLE IF EXISTS "evento" CASCADE;
DROP TABLE IF EXISTS "jugador" CASCADE;
DROP TABLE IF EXISTS "jugador_equipo" CASCADE;
DROP TABLE IF EXISTS "partido" CASCADE;
DROP TABLE IF EXISTS "programacion" CASCADE;
DROP TABLE IF EXISTS "tarifa" CASCADE;
DROP TABLE IF EXISTS "tipo_evento" CASCADE;
DROP TABLE IF EXISTS "usuario" CASCADE;

--CREAMOS LAS TABLAS.
CREATE TABLE "cancha" ("id_cancha" INT, "nombre" VARCHAR(50));
CREATE TABLE "categoria" ("id_categoria" INT, "nombre" VARCHAR(50), "edad_minima" INT, "edad_maxima" INT);
CREATE TABLE "comuna" ("nombre" VARCHAR(100), "id" INT);
CREATE TABLE "equipo" ("id_equipo" INT, "nombre" VARCHAR(50), "cantidad_jugador" INT, "fecha_creacion" DATE, "id_categoria" INT);
CREATE TABLE "evento" ("id_evento" INT, "id_partido" INT, "rut_jugador" INT, "minuto" INT, "equipo_local" VARCHAR(50), "equipo_visita" VARCHAR(50), "equipo_jugador" VARCHAR(50), "id_tipo_evento" VARCHAR(2), "fecha" DATE, "nombre_jugador" VARCHAR(50), "apellido_jugador" VARCHAR(50), "camiseta" INT);
CREATE TABLE "jugador" ("rut" INT, "dv" CHAR(1), "nombre" VARCHAR(50), "apellido" VARCHAR(50));
CREATE TABLE "jugador_equipo" ("id_jugador_equipo" INT, "fecha_incorporacion" DATE, "camiseta" VARCHAR(3), "id_equipo" INT, "rut_jugador" INT);
CREATE TABLE "partido" ("id_partido" INT, "id_programacion" INT, "inicio" TIMESTAMP (6), "fin" TIMESTAMP (6), "goles_local" INT, "goles_visita" INT, "id_equipo_local" INT, "id_equipo_visita" INT, "id_user" INT, "id_cancha" INT, "fecha" DATE, "equipo_local" VARCHAR(50), "equipo_visita" VARCHAR(50), "cancha" VARCHAR(50), "id_tarifa" INT DEFAULT 1);
CREATE TABLE "programacion" ("id_programacion" INT, "id_equipo_1" INT, "id_equipo_2" INT, "fecha" DATE, "hora" TIMESTAMP (6), "id_tarifa" INT, "valor_pagado" INT DEFAULT 0, "estado" CHAR(2) DEFAULT 'NJ', "equipo_1" VARCHAR(50), "equipo_2" VARCHAR(50), "minutos_jugados" INT);
CREATE TABLE "tarifa" ("id_tarifa" INT, "descripcion" VARCHAR(50), "valor" INT, "fecha_creacion" DATE, "fecha_actualizacion" DATE, "fecha_eliminacion" DATE, "id_user_creacion" INT, "id_user_actualizacion" INT, "id_user_eliminacion" INT);
CREATE TABLE "tipo_evento" ("descripcion" VARCHAR(30), "relevante" CHAR(1) DEFAULT 'N', "id_tipo_evento" VARCHAR(2));
CREATE TABLE "usuario" ("id_user" INT, "username" VARCHAR(50), "password" VARCHAR(50), "fecha_creacion" DATE, "fecha_bloqueo" DATE, "nombre" VARCHAR(50), "apellido" VARCHAR(50));

-- SE INSERTAN LOS DATOS DE PRUEBA

INSERT INTO cancha (id_cancha,nombre) VALUES ('1','NAPOLES');
INSERT INTO cancha (id_cancha,nombre) VALUES ('2','MILAN');
INSERT INTO cancha (id_cancha,nombre) VALUES ('3','MESSINA');
INSERT INTO cancha (id_cancha,nombre) VALUES ('4','ROMA');
INSERT INTO cancha (id_cancha,nombre) VALUES ('5','LIVORNO');
INSERT INTO cancha (id_cancha,nombre) VALUES ('6','VENECIA');
INSERT INTO cancha (id_cancha,nombre) VALUES ('7','TURIN');
INSERT INTO cancha (id_cancha,nombre) VALUES ('8','FLORENCIA');

INSERT INTO categoria (id_categoria,nombre,edad_minima,edad_maxima) VALUES ('2','PROFESIONAL','18','40');
INSERT INTO categoria (id_categoria,nombre,edad_minima,edad_maxima) VALUES ('3','EMPRESA','18','55');
INSERT INTO categoria (id_categoria,nombre,edad_minima,edad_maxima) VALUES ('4','JUNIOR','8','13');
INSERT INTO categoria (id_categoria,nombre,edad_minima,edad_maxima) VALUES ('1','AMATEUR','14','17');

INSERT INTO comuna (nombre,ID) VALUES ('Santiago','1');
INSERT INTO comuna (nombre,ID) VALUES ('Cerrillos','2');
INSERT INTO comuna (nombre,ID) VALUES ('Cerro Navia','3');
INSERT INTO comuna (nombre,ID) VALUES ('Puente Alto','4');
INSERT INTO comuna (nombre,ID) VALUES ('Pirque','5');
INSERT INTO comuna (nombre,ID) VALUES ('Conchalí','6');
INSERT INTO comuna (nombre,ID) VALUES ('El Bosque','7');
INSERT INTO comuna (nombre,ID) VALUES ('Estación Central','8');
INSERT INTO comuna (nombre,ID) VALUES ('Huechuraba','9');
INSERT INTO comuna (nombre,ID) VALUES ('Independencia','10');
INSERT INTO comuna (nombre,ID) VALUES ('La Cisterna','11');
INSERT INTO comuna (nombre,ID) VALUES ('La FlorIDa','12');
INSERT INTO comuna (nombre,ID) VALUES ('La Granja','13');
INSERT INTO comuna (nombre,ID) VALUES ('La Pintana','14');
INSERT INTO comuna (nombre,ID) VALUES ('La Reina','15');
INSERT INTO comuna (nombre,ID) VALUES ('Las Condes','16');
INSERT INTO comuna (nombre,ID) VALUES ('Lo Barnechea','17');
INSERT INTO comuna (nombre,ID) VALUES ('Lo Espejo','18');
INSERT INTO comuna (nombre,ID) VALUES ('Lo Prado','19');
INSERT INTO comuna (nombre,ID) VALUES ('Macul','20');
INSERT INTO comuna (nombre,ID) VALUES ('Maipú','21');
INSERT INTO comuna (nombre,ID) VALUES ('Ñuñoa','22');
INSERT INTO comuna (nombre,ID) VALUES ('Pedro Aguirre Cerda','23');
INSERT INTO comuna (nombre,ID) VALUES ('Peñalolén','24');
INSERT INTO comuna (nombre,ID) VALUES ('ProvIDencia','25');
INSERT INTO comuna (nombre,ID) VALUES ('Pudahuel','26');
INSERT INTO comuna (nombre,ID) VALUES ('Quilicura','27');
INSERT INTO comuna (nombre,ID) VALUES ('Quinta Normal','28');
INSERT INTO comuna (nombre,ID) VALUES ('Recoleta','29');
INSERT INTO comuna (nombre,ID) VALUES ('Renca','30');
INSERT INTO comuna (nombre,ID) VALUES ('San Joaquín','31');
INSERT INTO comuna (nombre,ID) VALUES ('San Miguel','32');
INSERT INTO comuna (nombre,ID) VALUES ('San Ramón','33');
INSERT INTO comuna (nombre,ID) VALUES ('Vitacura','34');
INSERT INTO comuna (nombre,ID) VALUES ('San José de Maipo','35');
INSERT INTO comuna (nombre,ID) VALUES ('Colina','36');
INSERT INTO comuna (nombre,ID) VALUES ('Lampa','37');
INSERT INTO comuna (nombre,ID) VALUES ('Tiltil','38');
INSERT INTO comuna (nombre,ID) VALUES ('San Bernardo','39');
INSERT INTO comuna (nombre,ID) VALUES ('Buin','40');
INSERT INTO comuna (nombre,ID) VALUES ('Calera de Tango','41');
INSERT INTO comuna (nombre,ID) VALUES ('Paine','42');
INSERT INTO comuna (nombre,ID) VALUES ('Melipilla','43');
INSERT INTO comuna (nombre,ID) VALUES ('Alhué','44');
INSERT INTO comuna (nombre,ID) VALUES ('Curacaví','45');
INSERT INTO comuna (nombre,ID) VALUES ('María PINTO','46');
INSERT INTO comuna (nombre,ID) VALUES ('San Pedro','47');
INSERT INTO comuna (nombre,ID) VALUES ('Talagante','48');
INSERT INTO comuna (nombre,ID) VALUES ('El Monte','49');
INSERT INTO comuna (nombre,ID) VALUES ('Isla de Maipo','50');
INSERT INTO comuna (nombre,ID) VALUES ('Padre Hurtado','51');
INSERT INTO comuna (nombre,ID) VALUES ('Peñaflor','52');

INSERT INTO equipo (id_equipo,nombre,cantidad_jugador,fecha_creacion,id_categoria) VALUES ('3','TELETUBBIES','8',to_date('14/11/17','DD/MM/YY'),'4');
INSERT INTO equipo (id_equipo,nombre,cantidad_jugador,fecha_creacion,id_categoria) VALUES ('4','CACHORROS','8',to_date('14/11/17','DD/MM/YY'),'4');
INSERT INTO equipo (id_equipo,nombre,cantidad_jugador,fecha_creacion,id_categoria) VALUES ('5','DEVASTADORES','9',to_date('12/01/18','DD/MM/YY'),'1');
INSERT INTO equipo (id_equipo,nombre,cantidad_jugador,fecha_creacion,id_categoria) VALUES ('6','DON JUAN FC','9',to_date('13/06/18','DD/MM/YY'),'1');
INSERT INTO equipo (id_equipo,nombre,cantidad_jugador,fecha_creacion,id_categoria) VALUES ('7','STOLICHVAYA','9',to_date('01/01/18','DD/MM/YY'),'1');
INSERT INTO equipo (id_equipo,nombre,cantidad_jugador,fecha_creacion,id_categoria) VALUES ('8','OLIMPIA','9',to_date('06/02/18','DD/MM/YY'),'1');
INSERT INTO equipo (id_equipo,nombre,cantidad_jugador,fecha_creacion,id_categoria) VALUES ('9','LOGISTICA','9',to_date('02/06/18','DD/MM/YY'),'3');
INSERT INTO equipo (id_equipo,nombre,cantidad_jugador,fecha_creacion,id_categoria) VALUES ('10','BODEGA','9',to_date('02/06/18','DD/MM/YY'),'3');
INSERT INTO equipo (id_equipo,nombre,cantidad_jugador,fecha_creacion,id_categoria) VALUES ('11','CONTABILIDAD','9',to_date('02/06/18','DD/MM/YY'),'3');
INSERT INTO equipo (id_equipo,nombre,cantidad_jugador,fecha_creacion,id_categoria) VALUES ('12','INFORMATICA','9',to_date('02/06/18','DD/MM/YY'),'3');
INSERT INTO equipo (id_equipo,nombre,cantidad_jugador,fecha_creacion,id_categoria) VALUES ('1','GRINGUITOS','8',to_date('14/11/17','DD/MM/YY'),'4');
INSERT INTO equipo (id_equipo,nombre,cantidad_jugador,fecha_creacion,id_categoria) VALUES ('2','PINGUINOS','8',to_date('14/11/17','DD/MM/YY'),'4');

INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('1','1','8801699','89','TELETUBBIES','CACHORROS','TELETUBBIES','GL',to_date('15/08/18','DD/MM/YY'),'ERIK','ARAYA ','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('2','1','8801699','68','TELETUBBIES','CACHORROS','TELETUBBIES','GL',to_date('15/08/18','DD/MM/YY'),'ERIK','ARAYA ','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('3','1','8801699','54','TELETUBBIES','CACHORROS','TELETUBBIES','GL',to_date('15/08/18','DD/MM/YY'),'ERIK','ARAYA ','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('4','1','12141116','80','TELETUBBIES','CACHORROS','CACHORROS','GL',to_date('15/08/18','DD/MM/YY'),'CRISTIAN','CRUZ','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('5','2','1669343','45','GRINGUITOS','PINGUINOS','GRINGUITOS','GL',to_date('15/08/18','DD/MM/YY'),'WALTER RAUL ','PEREZ ','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('6','2','1669343','54','GRINGUITOS','PINGUINOS','GRINGUITOS','GL',to_date('15/08/18','DD/MM/YY'),'WALTER RAUL ','PEREZ ','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('7','5','38647112','5','LOGISTICA','BODEGA','LOGISTICA','GL',to_date('17/08/18','DD/MM/YY'),'JOSE RENE','ZAPATA','10');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('8','5','38647112','74','LOGISTICA','BODEGA','LOGISTICA','GL',to_date('17/08/18','DD/MM/YY'),'JOSE RENE','ZAPATA','10');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('9','5','38647112','79','LOGISTICA','BODEGA','LOGISTICA','GL',to_date('17/08/18','DD/MM/YY'),'JOSE RENE','ZAPATA','10');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('10','5','38647112','22','LOGISTICA','BODEGA','LOGISTICA','GL',to_date('17/08/18','DD/MM/YY'),'JOSE RENE','ZAPATA','10');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('11','5','38647112','36','LOGISTICA','BODEGA','LOGISTICA','GL',to_date('17/08/18','DD/MM/YY'),'JOSE RENE','ZAPATA','10');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('12','5','47072543','79','LOGISTICA','BODEGA','BODEGA','GL',to_date('17/08/18','DD/MM/YY'),'CAMILO','CARVACHO','10');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('13','5','47072543','76','LOGISTICA','BODEGA','BODEGA','GL',to_date('17/08/18','DD/MM/YY'),'CAMILO','CARVACHO','10');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('14','5','47072543','78','LOGISTICA','BODEGA','BODEGA','GL',to_date('17/08/18','DD/MM/YY'),'CAMILO','CARVACHO','10');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('15','5','47072543','25','LOGISTICA','BODEGA','BODEGA','GL',to_date('17/08/18','DD/MM/YY'),'CAMILO','CARVACHO','10');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('16','5','47072543','67','LOGISTICA','BODEGA','BODEGA','GL',to_date('17/08/18','DD/MM/YY'),'CAMILO','CARVACHO','10');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('17','5','47072543','80','LOGISTICA','BODEGA','BODEGA','GL',to_date('17/08/18','DD/MM/YY'),'CAMILO','CARVACHO','10');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('18','5','47072543','93','LOGISTICA','BODEGA','BODEGA','GL',to_date('17/08/18','DD/MM/YY'),'CAMILO','CARVACHO','10');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('19','6','58950320','62','INFORMATICA','CONTABILIDAD','INFORMATICA','GL',to_date('17/08/18','DD/MM/YY'),'JOSE ','FUENTES ','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('20','6','58950320','38','INFORMATICA','CONTABILIDAD','INFORMATICA','GL',to_date('17/08/18','DD/MM/YY'),'JOSE ','FUENTES ','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('21','6','58950320','5','INFORMATICA','CONTABILIDAD','INFORMATICA','GL',to_date('17/08/18','DD/MM/YY'),'JOSE ','FUENTES ','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('22','6','58950320','19','INFORMATICA','CONTABILIDAD','INFORMATICA','GL',to_date('17/08/18','DD/MM/YY'),'JOSE ','FUENTES ','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('23','6','58950320','75','INFORMATICA','CONTABILIDAD','INFORMATICA','GL',to_date('17/08/18','DD/MM/YY'),'JOSE ','FUENTES ','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('24','6','54036880','53','INFORMATICA','CONTABILIDAD','CONTABILIDAD','GL',to_date('17/08/18','DD/MM/YY'),'FRANCESCO','MATHEU','9');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('25','6','54036880','46','INFORMATICA','CONTABILIDAD','CONTABILIDAD','GL',to_date('17/08/18','DD/MM/YY'),'FRANCESCO','MATHEU','9');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('26','6','54036880','49','INFORMATICA','CONTABILIDAD','CONTABILIDAD','GL',to_date('17/08/18','DD/MM/YY'),'FRANCESCO','MATHEU','9');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('27','6','54036880','66','INFORMATICA','CONTABILIDAD','CONTABILIDAD','GL',to_date('17/08/18','DD/MM/YY'),'FRANCESCO','MATHEU','9');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('28','9','20322516','7','DON JUAN FC','DEVASTADORES','DEVASTADORES','GL',to_date('19/08/18','DD/MM/YY'),'DANIEL LEOPOLDO','DIAZ','9');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('29','10','37158020','75','STOLICHVAYA','OLIMPIA','OLIMPIA','GL',to_date('19/08/18','DD/MM/YY'),'PATRICIO','MARIN','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('30','11','38647112','39','BODEGA','LOGISTICA','LOGISTICA','GL',to_date('19/08/18','DD/MM/YY'),'JOSE RENE','ZAPATA','10');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('31','11','38647112','33','BODEGA','LOGISTICA','LOGISTICA','GL',to_date('19/08/18','DD/MM/YY'),'JOSE RENE','ZAPATA','10');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('32','14','12141116','32','CACHORROS','GRINGUITOS','CACHORROS','GL',to_date('20/08/18','DD/MM/YY'),'CRISTIAN','CRUZ','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('33','14','12141116','92','CACHORROS','GRINGUITOS','CACHORROS','GL',to_date('20/08/18','DD/MM/YY'),'CRISTIAN','CRUZ','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('34','14','12141116','44','CACHORROS','GRINGUITOS','CACHORROS','GL',to_date('20/08/18','DD/MM/YY'),'CRISTIAN','CRUZ','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('35','14','12141116','87','CACHORROS','GRINGUITOS','CACHORROS','GL',to_date('20/08/18','DD/MM/YY'),'CRISTIAN','CRUZ','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('36','14','12141116','80','CACHORROS','GRINGUITOS','CACHORROS','GL',to_date('20/08/18','DD/MM/YY'),'CRISTIAN','CRUZ','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('37','14','12141116','2','CACHORROS','GRINGUITOS','CACHORROS','GL',to_date('20/08/18','DD/MM/YY'),'CRISTIAN','CRUZ','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('38','14','12141116','93','CACHORROS','GRINGUITOS','CACHORROS','GL',to_date('20/08/18','DD/MM/YY'),'CRISTIAN','CRUZ','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('39','14','1669343','74','CACHORROS','GRINGUITOS','GRINGUITOS','GL',to_date('20/08/18','DD/MM/YY'),'WALTER RAUL ','PEREZ ','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('40','14','1669343','47','CACHORROS','GRINGUITOS','GRINGUITOS','GL',to_date('20/08/18','DD/MM/YY'),'WALTER RAUL ','PEREZ ','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('41','14','1669343','78','CACHORROS','GRINGUITOS','GRINGUITOS','GL',to_date('20/08/18','DD/MM/YY'),'WALTER RAUL ','PEREZ ','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('42','14','1669343','53','CACHORROS','GRINGUITOS','GRINGUITOS','GL',to_date('20/08/18','DD/MM/YY'),'WALTER RAUL ','PEREZ ','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('43','14','1669343','21','CACHORROS','GRINGUITOS','GRINGUITOS','GL',to_date('20/08/18','DD/MM/YY'),'WALTER RAUL ','PEREZ ','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('44','15','29585336','63','STOLICHVAYA','DEVASTADORES','STOLICHVAYA','GL',to_date('20/08/18','DD/MM/YY'),'GUIDO','FARIAS','10');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('45','15','29585336','60','STOLICHVAYA','DEVASTADORES','STOLICHVAYA','GL',to_date('20/08/18','DD/MM/YY'),'GUIDO','FARIAS','10');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('46','15','20322516','88','STOLICHVAYA','DEVASTADORES','DEVASTADORES','GL',to_date('20/08/18','DD/MM/YY'),'DANIEL LEOPOLDO','DIAZ','9');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('47','15','20322516','59','STOLICHVAYA','DEVASTADORES','DEVASTADORES','GL',to_date('20/08/18','DD/MM/YY'),'DANIEL LEOPOLDO','DIAZ','9');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('48','15','20322516','43','STOLICHVAYA','DEVASTADORES','DEVASTADORES','GL',to_date('20/08/18','DD/MM/YY'),'DANIEL LEOPOLDO','DIAZ','9');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('49','15','20322516','73','STOLICHVAYA','DEVASTADORES','DEVASTADORES','GL',to_date('20/08/18','DD/MM/YY'),'DANIEL LEOPOLDO','DIAZ','9');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('50','15','20322516','12','STOLICHVAYA','DEVASTADORES','DEVASTADORES','GL',to_date('20/08/18','DD/MM/YY'),'DANIEL LEOPOLDO','DIAZ','9');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('51','15','20322516','25','STOLICHVAYA','DEVASTADORES','DEVASTADORES','GL',to_date('20/08/18','DD/MM/YY'),'DANIEL LEOPOLDO','DIAZ','9');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('52','16','23061531','81','DON JUAN FC','OLIMPIA','DON JUAN FC','GL',to_date('21/08/18','DD/MM/YY'),'DAVID','CANCINO','9');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('53','16','23061531','23','DON JUAN FC','OLIMPIA','DON JUAN FC','GL',to_date('21/08/18','DD/MM/YY'),'DAVID','CANCINO','9');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('54','16','23061531','93','DON JUAN FC','OLIMPIA','DON JUAN FC','GL',to_date('21/08/18','DD/MM/YY'),'DAVID','CANCINO','9');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('55','16','37158020','23','DON JUAN FC','OLIMPIA','OLIMPIA','GL',to_date('21/08/18','DD/MM/YY'),'PATRICIO','MARIN','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('56','17','38647112','40','CONTABILIDAD','LOGISTICA','LOGISTICA','GL',to_date('21/08/18','DD/MM/YY'),'JOSE RENE','ZAPATA','10');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('57','20','54036880','22','CONTABILIDAD','CACHORROS','CONTABILIDAD','GL',to_date('23/08/18','DD/MM/YY'),'FRANCESCO','MATHEU','9');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('58','21','37158020','25','OLIMPIA','DEVASTADORES','OLIMPIA','GL',to_date('23/08/18','DD/MM/YY'),'PATRICIO','MARIN','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('59','21','37158020','86','OLIMPIA','DEVASTADORES','OLIMPIA','GL',to_date('23/08/18','DD/MM/YY'),'PATRICIO','MARIN','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('60','21','20322516','26','OLIMPIA','DEVASTADORES','DEVASTADORES','GL',to_date('23/08/18','DD/MM/YY'),'DANIEL LEOPOLDO','DIAZ','9');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('61','26','37158020','92','CONTABILIDAD','OLIMPIA','OLIMPIA','GL',to_date('26/08/18','DD/MM/YY'),'PATRICIO','MARIN','11');
INSERT INTO evento (id_evento,id_partido,rut_jugador,minuto,equipo_local,equipo_visita,equipo_jugador,id_tipo_evento,fecha,nombre_jugador,apellido_jugador,camiseta) VALUES ('62','27','20322516','38','BODEGA','DEVASTADORES','DEVASTADORES','GL',to_date('27/08/18','DD/MM/YY'),'DANIEL LEOPOLDO','DIAZ','9');

INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('98326882','K','Hilel','VIDAL');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('24809221','1','Zeph','CORVAL�?N');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('71629611','3','Gannon','RUIZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('87602978','2','Neville','VILLAGÓMEZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('59166208','2','Marvin','ROJAS ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('23061531','4','Samson','CANCINO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('2194920','5','Tyler','ORLANDO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('52536075','K','Neville','CORTES');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('5281817','6','Adam','GUERRERO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('76762745','9','Fitzgerald','AGUIRRE ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('25405449','6','Kasimir','VALDES');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('53074745','K','Sawyer','MORALES');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('61935771','K','Dante','RUIZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('56848279','4','Tate','GUITAL');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('95435955','7','Berk','FUENZALIDA');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('17166549','3','Colt','SALAS');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('21898020','1','Colton','MELENDES');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('64226636','5','Kamal','HUENCHULAO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('59088863','K','Declan','ALVAREZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('84735838','6','Magee','ROKY');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('3018117','4','Plato','JURICIC');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('17255206','4','Carlos','SANDOVAL');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('68461289','1','Ray','VASQUEZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('87069852','6','Callum','UGEL');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('74411676','7','Abdul','SOTO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('1394262','5','Derek','ASTUDILLO ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('53223034','9','Zahir','TOLOZA');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('55007800','7','Marshall','MORA');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('35098122','5','Forrest','CORVAL�?N');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('29965487','7','Melvin','SANDROCK');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('31588155','2','Alexander','TAPIA');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('28143035','1','Berk','PIZARRO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('31421030','1','Herrod','GRUSIC');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('81621802','0','Hammett','VALENZUELA');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('24498120','8','Barry','MUÑOZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('95706709','3','Driscoll','PRIETO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('8676153','K','Elvis','GONZALEZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('4448142','1','Nathan','RIFO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('56816611','6','Dorian','ITURRIAGA');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('40928167','2','Rahim','GARETTO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('87859171','2','Hamilton','ALLENDE ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('95649644','6','Vance','MORA');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('69360054','5','Barclay','ROJAS ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('71291573','0','Ahmed','MARIN');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('3438218','2','Nissim','BURGOS');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('98704176','5','Jamal','MATUS');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('69107184','7','Vincent','LEON');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('52307509','8','Oliver','GOMEZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('80224656','0','Joseph','AGUILERA');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('37196455','K','Gil','CORTES ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('87411834','6','Keegan','CASTRO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('38463171','1','Bevis','CASTRO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('75528696','6','Driscoll','ALLENDES ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('37158020','4','Silas','MARIN');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('34821345','8','Galvin','ACEVEDO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('29769217','8','Ivan','MORENO ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('9539267','9','Kyle','PEREZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('52251926','K','Micah','REBELLAUT');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('1512379','6','Clark','CASTILLO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('45577349','0','Oren','MAZO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('14051531','0','Hunter','CANTILLANA');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('43047268','2','Hamish','CASTILLANA');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('60810081','4','Nehru','FREIRE');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('19612878','6','Austin','OPAZO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('77744173','6','Asher','EBENSPERGER');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('39476444','2','Kato','GUTIERREZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('9679940','3','Thane','OPAZO ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('66939180','3','Alec','OPAZO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('97131457','5','Kibo','TOLOSA ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('7901645','4','Lars','VILLARROEL');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('41906482','3','Roth','VALDERRAMA');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('83705190','8','Adam','CARVACHO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('47072543','5','Keane','CARVACHO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('88678790','1','Arden','JARAMILLO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('78864381','0','Travis','RIOS');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('95935409','K','August','ALVAREZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('60647857','7','Vernon','SOTOMAYOR');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('30817381','K','Hunter','BARBAZZO ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('10038488','4','Philip','BUSTAMANTE');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('62971708','0','Louis','FARFAN');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('37734232','1','Ciaran','ELGUETA ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('80153372','8','Flynn','ALEGRIA ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('62584238','7','Salvador','MORAGA');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('3539534','2','Hedley','MATHEU');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('74632336','0','Wang','VIDAL');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('54036880','5','Jerome','MATHEU');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('1669343','K','Nash','PEREZ ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('73358089','5','Dexter','VELASQUEZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('79196815','1','Rogan','VERA');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('29425171','5','Mannix','LANDMAN');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('12141116','4','Oren','CRUZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('82532139','K','Lamar','VELASQUEZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('87505402','3','Kermit','MARDONES');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('80481373','K','August','MERCADO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('2040747','6','Walter','MEND');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('47269316','6','Gavin','MENDOZA');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('20500351','7','Paki','BUSTOS');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('20254800','8','Calvin','RAMIREZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('29585336','0','Lars','FARIAS');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('535669','5','Andrew','CAPURRO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('27570413','K','Dolan','PAVEZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('90108466','1','Gil','CASTRO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('49464632','3','Brett','CAÑAS');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('5845793','0','Colin','DIOCARES');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('38647112','6','Hiram','ZAPATA');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('75432051','6','Arden','CASTILLO ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('95844772','8','Jonas','PINTO ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('22968901','0','Cooper','GUTIERREZ ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('67487285','2','Darius','BOIZARD');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('33209034','8','Erich','DE SOLMINIHAC ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('8299751','2','Thomas','VIZCARRA');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('52790811','6','Benjamin','JELDRES');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('93491939','4','Victor','COSTA ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('69186761','7','Honorato','RAMIREZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('80194418','3','Lewis','MARQUEZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('45427375','3','Stuart','YAÑEZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('20322516','4','Bert','DIAZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('5289556','1','Colorado','OLMEDO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('38370020','5','Kevin','IBARRA');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('57189858','6','Murphy','RODRIGUEZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('30213987','3','Honorato','RODRIGUEZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('22345651','0','Ezekiel','PONTIGO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('7583193','5','Rudyard','ROZAS');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('21364643','5','Erasmus','ARACENA');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('81241666','9','Wade','ESTEVES');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('86403645','7','Ryder','MORA ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('52024078','0','Reed','CABELLO ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('94868574','4','Rogan','CASTELLANOS ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('82896932','3','Quentin','GONZALEZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('58950320','1','Dennis','FUENTES ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('5586435','7','Garrison','TENRROZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('92806065','9','Laith','SALAZAR');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('58232331','3','Arden','REYES');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('17665094','K','Phelan','SALAS ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('60276134','7','Marshall','VILLAGRA ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('33266578','2','Alvin','MORALES ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('12987266','7','Tyrone','ARANCIBIA');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('54806654','9','Lucius','NIEDERMAYR');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('15905690','2','Wallace','PEREZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('19768693','6','Xanthus','CABEZAS');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('28297306','5','Chancellor','MARTINEZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('9002811','1','Isaiah','SEPULVEDA');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('78614529','5','Nigel','FERNANDEZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('93839085','1','Barclay','YAÑEZ ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('25536358','1','Wang','NARVAEZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('79169157','5','Upton','VERA');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('98949453','8','Lester','CHAVEZ ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('24472749','2','Abdul','ARANGUIZ ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('95774105','3','Hop','GONZALEZ ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('44653774','1','Aladdin','GONZALEZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('8801699','8','Rafael','ARAYA ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('46944450','3','Kaseem','PIZARRO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('11879295','5','Holmes','PACHECO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('82409872','7','Jonah','MANCILLA ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('93613285','5','Melvin','MORENO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('67777880','6','Kennedy','PASTENE');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('15659921','2','Austin','SEVILLA');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('52592973','6','Lane','SEVILLA ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('61825827','0','Donovan','LANDABUR');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('27961478','K','Stuart','DE LA HARPE ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('72765170','5','Beck','HERMOSILLA ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('87626168','5','Kaseem','BELTRAN ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('94746634','8','Hop','COX');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('47221583','3','Jonah','VIDAL ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('95046566','2','Abdul','ESPEJO');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('88078561','3','Hop','MENDEZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('58597347','5','Kennedy','MARTINEZ');
INSERT INTO jugador (rut,DV,nombre,apellido) VALUES ('47551798','9','Rafael','GATICA');

INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('1',to_date('20/07/18','DD/MM/YY'),'1','1','535669');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('2',to_date('20/07/18','DD/MM/YY'),'2','1','1394262');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('3',to_date('20/07/18','DD/MM/YY'),'3','1','1512379');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('4',to_date('20/07/18','DD/MM/YY'),'11','1','1669343');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('5',to_date('20/07/18','DD/MM/YY'),'7','1','2040747');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('6',to_date('20/07/18','DD/MM/YY'),'8','1','2194920');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('7',to_date('20/07/18','DD/MM/YY'),'5','1','3018117');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('8',to_date('20/07/18','DD/MM/YY'),'9','1','3438218');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('9',to_date('20/07/18','DD/MM/YY'),'10','2','3539534');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('10',to_date('20/07/18','DD/MM/YY'),'5','2','4448142');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('11',to_date('20/07/18','DD/MM/YY'),'7','2','5281817');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('12',to_date('20/07/18','DD/MM/YY'),'1','2','5289556');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('13',to_date('20/07/18','DD/MM/YY'),'11','2','5586435');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('14',to_date('20/07/18','DD/MM/YY'),'6','2','5845793');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('15',to_date('20/07/18','DD/MM/YY'),'9','2','7583193');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('16',to_date('20/07/18','DD/MM/YY'),'3','2','7901645');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('17',to_date('20/07/18','DD/MM/YY'),'7','3','8299751');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('18',to_date('20/07/18','DD/MM/YY'),'5','3','8676153');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('19',to_date('20/07/18','DD/MM/YY'),'11','3','8801699');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('20',to_date('20/07/18','DD/MM/YY'),'8','3','9002811');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('21',to_date('20/07/18','DD/MM/YY'),'3','3','9539267');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('22',to_date('20/07/18','DD/MM/YY'),'10','3','9679940');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('23',to_date('20/07/18','DD/MM/YY'),'9','3','10038488');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('24',to_date('20/07/18','DD/MM/YY'),'1','3','11879295');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('25',to_date('20/07/18','DD/MM/YY'),'11','4','12141116');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('26',to_date('20/07/18','DD/MM/YY'),'10','4','12987266');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('27',to_date('20/07/18','DD/MM/YY'),'1','4','14051531');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('28',to_date('20/07/18','DD/MM/YY'),'9','4','15659921');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('29',to_date('20/07/18','DD/MM/YY'),'7','4','15905690');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('30',to_date('20/07/18','DD/MM/YY'),'3','4','17166549');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('31',to_date('20/07/18','DD/MM/YY'),'5','4','17255206');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('32',to_date('20/07/18','DD/MM/YY'),'8','4','17665094');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('33',to_date('20/07/18','DD/MM/YY'),'6','5','19612878');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('34',to_date('20/07/18','DD/MM/YY'),'8','5','19768693');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('35',to_date('20/07/18','DD/MM/YY'),'1','5','20254800');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('36',to_date('20/07/18','DD/MM/YY'),'9','5','20322516');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('37',to_date('20/07/18','DD/MM/YY'),'7','5','20500351');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('38',to_date('20/07/18','DD/MM/YY'),'11','5','21364643');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('39',to_date('20/07/18','DD/MM/YY'),'2','5','21898020');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('40',to_date('20/07/18','DD/MM/YY'),'10','5','22345651');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('41',to_date('20/07/18','DD/MM/YY'),'3','5','22968901');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('42',to_date('20/07/18','DD/MM/YY'),'9','6','23061531');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('43',to_date('20/07/18','DD/MM/YY'),'5','6','24472749');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('44',to_date('20/07/18','DD/MM/YY'),'6','6','24498120');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('45',to_date('20/07/18','DD/MM/YY'),'1','6','24809221');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('46',to_date('20/07/18','DD/MM/YY'),'7','6','25405449');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('47',to_date('20/07/18','DD/MM/YY'),'4','6','25536358');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('48',to_date('20/07/18','DD/MM/YY'),'11','6','27570413');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('49',to_date('20/07/18','DD/MM/YY'),'10','6','27961478');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('50',to_date('20/07/18','DD/MM/YY'),'3','6','28143035');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('51',to_date('20/07/18','DD/MM/YY'),'3','7','28297306');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('52',to_date('20/07/18','DD/MM/YY'),'5','7','29425171');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('53',to_date('20/07/18','DD/MM/YY'),'10','7','29585336');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('54',to_date('20/07/18','DD/MM/YY'),'8','7','29769217');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('55',to_date('20/07/18','DD/MM/YY'),'7','7','29965487');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('56',to_date('20/07/18','DD/MM/YY'),'6','7','30213987');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('57',to_date('20/07/18','DD/MM/YY'),'2','7','30817381');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('58',to_date('20/07/18','DD/MM/YY'),'1','7','31421030');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('59',to_date('20/07/18','DD/MM/YY'),'9','7','31588155');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('60',to_date('20/07/18','DD/MM/YY'),'3','8','33209034');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('61',to_date('20/07/18','DD/MM/YY'),'1','8','33266578');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('62',to_date('20/07/18','DD/MM/YY'),'5','8','34821345');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('63',to_date('20/07/18','DD/MM/YY'),'7','8','35098122');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('64',to_date('20/07/18','DD/MM/YY'),'11','8','37158020');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('65',to_date('20/07/18','DD/MM/YY'),'9','8','37196455');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('66',to_date('20/07/18','DD/MM/YY'),'6','8','37734232');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('67',to_date('20/07/18','DD/MM/YY'),'4','8','38370020');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('68',to_date('20/07/18','DD/MM/YY'),'8','8','38463171');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('69',to_date('20/07/18','DD/MM/YY'),'10','9','38647112');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('70',to_date('20/07/18','DD/MM/YY'),'1','9','39476444');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('71',to_date('20/07/18','DD/MM/YY'),'5','9','40928167');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('72',to_date('20/07/18','DD/MM/YY'),'7','9','41906482');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('73',to_date('20/07/18','DD/MM/YY'),'9','9','43047268');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('74',to_date('20/07/18','DD/MM/YY'),'2','9','44653774');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('75',to_date('20/07/18','DD/MM/YY'),'11','9','45427375');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('76',to_date('20/07/18','DD/MM/YY'),'8','9','45577349');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('77',to_date('20/07/18','DD/MM/YY'),'4','9','46944450');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('78',to_date('20/07/18','DD/MM/YY'),'10','10','47072543');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('79',to_date('20/07/18','DD/MM/YY'),'11','10','47221583');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('80',to_date('20/07/18','DD/MM/YY'),'1','10','47269316');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('81',to_date('20/07/18','DD/MM/YY'),'3','10','47551798');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('82',to_date('20/07/18','DD/MM/YY'),'9','10','49464632');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('83',to_date('20/07/18','DD/MM/YY'),'8','10','52024078');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('84',to_date('20/07/18','DD/MM/YY'),'5','10','52251926');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('85',to_date('20/07/18','DD/MM/YY'),'2','10','52307509');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('86',to_date('20/07/18','DD/MM/YY'),'6','10','52536075');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('87',to_date('20/07/18','DD/MM/YY'),'7','11','52592973');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('88',to_date('20/07/18','DD/MM/YY'),'8','11','52790811');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('89',to_date('20/07/18','DD/MM/YY'),'2','11','53074745');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('90',to_date('20/07/18','DD/MM/YY'),'1','11','53223034');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('91',to_date('20/07/18','DD/MM/YY'),'9','11','54036880');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('92',to_date('20/07/18','DD/MM/YY'),'7','11','54806654');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('93',to_date('20/07/18','DD/MM/YY'),'10','11','55007800');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('94',to_date('20/07/18','DD/MM/YY'),'3','11','56816611');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('95',to_date('20/07/18','DD/MM/YY'),'5','11','56848279');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('96',to_date('20/07/18','DD/MM/YY'),'5','12','57189858');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('97',to_date('20/07/18','DD/MM/YY'),'6','12','58232331');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('98',to_date('20/07/18','DD/MM/YY'),'8','12','58597347');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('99',to_date('20/07/18','DD/MM/YY'),'11','12','58950320');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('100',to_date('20/07/18','DD/MM/YY'),'7','12','59088863');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('101',to_date('20/07/18','DD/MM/YY'),'9','12','59166208');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('102',to_date('20/07/18','DD/MM/YY'),'3','12','60276134');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('103',to_date('20/07/18','DD/MM/YY'),'2','12','60647857');
INSERT INTO jugador_equipo (id_jugador_equipo,fecha_incorporacion,camiseta,id_equipo,rut_jugador) VALUES ('104',to_date('20/07/18','DD/MM/YY'),'1','12','60810081');

INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('1','1',to_timestamp('15/08/18 15:00:00,117854000','DD/MM/YY HH24:MI:SSXFF'),to_timestamp('15/08/18 16:59:00,000000000','DD/MM/YY HH24:MI:SSXFF'),'3','1','3','4','1','2',to_date('15/08/18','DD/MM/YY'),'TELETUBBIES','CACHORROS','MILAN','1');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('2','2',to_timestamp('15/08/18 15:00:00,117854000','DD/MM/YY HH24:MI:SSXFF'),to_timestamp('15/08/18 16:59:00,000000000','DD/MM/YY HH24:MI:SSXFF'),'2','0','1','2','3','3',to_date('15/08/18','DD/MM/YY'),'GRINGUITOS','PINGUINOS','MESSINA','1');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('3','3',to_timestamp('16/08/18 20:03:05,317341000','DD/MM/YY HH24:MI:SSXFF'),null,'0','0','5','6','2','5',to_date('16/08/18','DD/MM/YY'),'DEVASTADORES','DON JUAN FC','LIVORNO','3');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('4','4',to_timestamp('16/08/18 20:03:05,317341000','DD/MM/YY HH24:MI:SSXFF'),null,'0','0','8','7','1','8',to_date('16/08/18','DD/MM/YY'),'OLIMPIA','STOLICHVAYA','FLORENCIA','3');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('5','5',to_timestamp('17/08/18 16:00:00,285635000','DD/MM/YY HH24:MI:SSXFF'),to_timestamp('17/08/18 17:47:00,000000000','DD/MM/YY HH24:MI:SSXFF'),'5','7','9','10','4','7',to_date('17/08/18','DD/MM/YY'),'LOGISTICA','BODEGA','TURIN','2');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('6','6',to_timestamp('17/08/18 16:00:00,285635000','DD/MM/YY HH24:MI:SSXFF'),to_timestamp('17/08/18 17:47:00,000000000','DD/MM/YY HH24:MI:SSXFF'),'5','4','12','11','1','4',to_date('17/08/18','DD/MM/YY'),'INFORMATICA','CONTABILIDAD','ROMA','2');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('7','7',to_timestamp('18/08/18 18:15:00,000000000','DD/MM/YY HH24:MI:SSXFF'),null,'0','0','4','3','4','1',to_date('18/08/18','DD/MM/YY'),'CACHORROS','TELETUBBIES','NAPOLES','1');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('8','8',to_timestamp('18/08/18 18:15:00,000000000','DD/MM/YY HH24:MI:SSXFF'),null,'0','0','2','1','2','2',to_date('18/08/18','DD/MM/YY'),'PINGUINOS','GRINGUITOS','MILAN','1');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('9','9',to_timestamp('19/08/18 18:20:03,000000000','DD/MM/YY HH24:MI:SSXFF'),to_timestamp('19/08/18 20:19:03,000000000','DD/MM/YY HH24:MI:SSXFF'),'0','1','6','5','4','5',to_date('19/08/18','DD/MM/YY'),'DON JUAN FC','DEVASTADORES','LIVORNO','3');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('10','10',to_timestamp('19/08/18 18:20:03,000000000','DD/MM/YY HH24:MI:SSXFF'),to_timestamp('19/08/18 20:19:03,000000000','DD/MM/YY HH24:MI:SSXFF'),'0','1','7','8','3','4',to_date('19/08/18','DD/MM/YY'),'STOLICHVAYA','OLIMPIA','ROMA','3');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('11','11',to_timestamp('19/08/18 18:16:00,000000000','DD/MM/YY HH24:MI:SSXFF'),to_timestamp('19/08/18 20:15:00,000000000','DD/MM/YY HH24:MI:SSXFF'),'0','2','10','9','3','6',to_date('19/08/18','DD/MM/YY'),'BODEGA','LOGISTICA','VENECIA','2');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('12','12',to_timestamp('19/08/18 18:16:00,000000000','DD/MM/YY HH24:MI:SSXFF'),null,'0','0','11','12','1','3',to_date('19/08/18','DD/MM/YY'),'CONTABILIDAD','INFORMATICA','MESSINA','2');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('13','13',to_timestamp('20/08/18 18:15:00,000000000','DD/MM/YY HH24:MI:SSXFF'),null,'0','0','1','3','3','2',to_date('20/08/18','DD/MM/YY'),'GRINGUITOS','TELETUBBIES','MILAN','1');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('14','14',to_timestamp('20/08/18 18:15:00,000000000','DD/MM/YY HH24:MI:SSXFF'),to_timestamp('20/08/18 20:00:00,000000000','DD/MM/YY HH24:MI:SSXFF'),'7','5','4','1','3','5',to_date('20/08/18','DD/MM/YY'),'CACHORROS','GRINGUITOS','LIVORNO','1');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('15','15',to_timestamp('20/08/18 18:20:03,000000000','DD/MM/YY HH24:MI:SSXFF'),to_timestamp('20/08/18 20:05:03,000000000','DD/MM/YY HH24:MI:SSXFF'),'2','6','7','5','4','4',to_date('20/08/18','DD/MM/YY'),'STOLICHVAYA','DEVASTADORES','ROMA','3');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('16','16',to_timestamp('21/08/18 18:20:03,000000000','DD/MM/YY HH24:MI:SSXFF'),to_timestamp('21/08/18 20:07:03,000000000','DD/MM/YY HH24:MI:SSXFF'),'3','1','6','8','2','1',to_date('21/08/18','DD/MM/YY'),'DON JUAN FC','OLIMPIA','NAPOLES','3');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('17','17',to_timestamp('21/08/18 18:16:00,000000000','DD/MM/YY HH24:MI:SSXFF'),to_timestamp('21/08/18 20:03:00,000000000','DD/MM/YY HH24:MI:SSXFF'),'0','1','11','9','2','7',to_date('21/08/18','DD/MM/YY'),'CONTABILIDAD','LOGISTICA','TURIN','2');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('18','18',to_timestamp('22/08/18 18:16:00,000000000','DD/MM/YY HH24:MI:SSXFF'),null,'0','0','10','12','1','8',to_date('22/08/18','DD/MM/YY'),'BODEGA','INFORMATICA','FLORENCIA','2');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('19','19',to_timestamp('23/08/18 18:15:00,000000000','DD/MM/YY HH24:MI:SSXFF'),null,'0','0','10','3','2','8',to_date('23/08/18','DD/MM/YY'),'BODEGA','TELETUBBIES','FLORENCIA','1');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('20','20',to_timestamp('23/08/18 18:15:00,000000000','DD/MM/YY HH24:MI:SSXFF'),to_timestamp('23/08/18 20:11:00,000000000','DD/MM/YY HH24:MI:SSXFF'),'1','0','11','4','2','8',to_date('23/08/18','DD/MM/YY'),'CONTABILIDAD','CACHORROS','FLORENCIA','1');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('21','21',to_timestamp('23/08/18 18:20:03,000000000','DD/MM/YY HH24:MI:SSXFF'),to_timestamp('23/08/18 20:16:03,000000000','DD/MM/YY HH24:MI:SSXFF'),'2','1','8','5','1','5',to_date('23/08/18','DD/MM/YY'),'OLIMPIA','DEVASTADORES','LIVORNO','3');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('22','22',to_timestamp('24/08/18 18:20:03,000000000','DD/MM/YY HH24:MI:SSXFF'),to_timestamp('24/08/18 20:18:03,000000000','DD/MM/YY HH24:MI:SSXFF'),'0','0','6','2','4','4',to_date('24/08/18','DD/MM/YY'),'DON JUAN FC','PINGUINOS','ROMA','3');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('23','23',to_timestamp('24/08/18 18:16:00,000000000','DD/MM/YY HH24:MI:SSXFF'),null,'0','0','12','9','3','1',to_date('24/08/18','DD/MM/YY'),'INFORMATICA','LOGISTICA','NAPOLES','2');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('24','24',to_timestamp('24/08/18 18:16:00,000000000','DD/MM/YY HH24:MI:SSXFF'),null,'0','0','1','12','1','2',to_date('24/08/18','DD/MM/YY'),'GRINGUITOS','INFORMATICA','MILAN','2');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('25','25',to_timestamp('25/08/18 18:15:00,000000000','DD/MM/YY HH24:MI:SSXFF'),null,'0','0','6','3','2','3',to_date('25/08/18','DD/MM/YY'),'DON JUAN FC','TELETUBBIES','MESSINA','1');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('26','26',to_timestamp('26/08/18 18:15:00,000000000','DD/MM/YY HH24:MI:SSXFF'),to_timestamp('26/08/18 20:14:00,000000000','DD/MM/YY HH24:MI:SSXFF'),'0','1','11','8','4','2',to_date('26/08/18','DD/MM/YY'),'CONTABILIDAD','OLIMPIA','MILAN','1');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('27','27',to_timestamp('27/08/18 18:20:03,000000000','DD/MM/YY HH24:MI:SSXFF'),to_timestamp('27/08/18 20:05:03,000000000','DD/MM/YY HH24:MI:SSXFF'),'0','1','10','5','1','1',to_date('27/08/18','DD/MM/YY'),'BODEGA','DEVASTADORES','NAPOLES','3');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('28','28',to_timestamp('28/08/18 18:20:03,000000000','DD/MM/YY HH24:MI:SSXFF'),null,'0','0','6','1','2','5',to_date('28/08/18','DD/MM/YY'),'DON JUAN FC','GRINGUITOS','LIVORNO','3');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('29','29',to_timestamp('28/08/18 18:16:00,000000000','DD/MM/YY HH24:MI:SSXFF'),null,'0','0','12','4','1','5',to_date('28/08/18','DD/MM/YY'),'INFORMATICA','CACHORROS','LIVORNO','2');
INSERT INTO partido (id_partido,id_programacion,inicio,fin,goles_local,goles_visita,id_equipo_local,id_equipo_visita,id_user,id_cancha,fecha,equipo_local,equipo_visita,cancha,id_tarifa) VALUES ('30','30',to_timestamp('29/08/18 18:16:00,000000000','DD/MM/YY HH24:MI:SSXFF'),to_timestamp('29/08/18 20:08:00,000000000','DD/MM/YY HH24:MI:SSXFF'),'0','0','9','12','3','4',to_date('29/08/18','DD/MM/YY'),'LOGISTICA','INFORMATICA','ROMA','2');

INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('1','3','4',to_date('15/08/18','DD/MM/YY'),to_timestamp('15/08/18 15:00:00,117854000','DD/MM/YY HH24:MI:SSXFF'),'1','20000','J ','TELETUBBIES','CACHORROS','119');
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('2','1','2',to_date('15/08/18','DD/MM/YY'),to_timestamp('15/08/18 15:00:00,117854000','DD/MM/YY HH24:MI:SSXFF'),'1','20000','J ','GRINGUITOS','PINGUINOS','119');
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('3','5','6',to_date('16/08/18','DD/MM/YY'),to_timestamp('16/08/18 20:03:05,317341000','DD/MM/YY HH24:MI:SSXFF'),'3','25000','NJ','DEVASTADORES','DON JUAN FC',null);
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('4','8','7',to_date('16/08/18','DD/MM/YY'),to_timestamp('16/08/18 20:03:05,317341000','DD/MM/YY HH24:MI:SSXFF'),'3','30000','NJ','OLIMPIA','STOLICHVAYA',null);
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('5','9','10',to_date('17/08/18','DD/MM/YY'),to_timestamp('17/08/18 16:00:00,285635000','DD/MM/YY HH24:MI:SSXFF'),'2','40000','J ','LOGISTICA','BODEGA','107');
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('6','12','11',to_date('17/08/18','DD/MM/YY'),to_timestamp('17/08/18 16:00:00,285635000','DD/MM/YY HH24:MI:SSXFF'),'2','40000','J ','INFORMATICA','CONTABILIDAD','107');
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('7','4','3',to_date('18/08/18','DD/MM/YY'),to_timestamp('18/08/18 18:15:00,000000000','DD/MM/YY HH24:MI:SSXFF'),'1','15000','NJ','CACHORROS','TELETUBBIES',null);
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('8','2','1',to_date('18/08/18','DD/MM/YY'),to_timestamp('18/08/18 18:15:00,000000000','DD/MM/YY HH24:MI:SSXFF'),'1','10000','NJ','PINGUINOS','GRINGUITOS',null);
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('9','6','5',to_date('19/08/18','DD/MM/YY'),to_timestamp('19/08/18 18:20:03,000000000','DD/MM/YY HH24:MI:SSXFF'),'3','50000','J ','DON JUAN FC','DEVASTADORES','120');
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('10','7','8',to_date('19/08/18','DD/MM/YY'),to_timestamp('19/08/18 18:20:03,000000000','DD/MM/YY HH24:MI:SSXFF'),'3','50000','J ','STOLICHVAYA','OLIMPIA','120');
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('11','10','9',to_date('19/08/18','DD/MM/YY'),to_timestamp('19/08/18 18:16:00,000000000','DD/MM/YY HH24:MI:SSXFF'),'2','40000','J ','BODEGA','LOGISTICA','120');
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('12','11','12',to_date('19/08/18','DD/MM/YY'),to_timestamp('19/08/18 18:16:00,000000000','DD/MM/YY HH24:MI:SSXFF'),'2','20000','NJ','CONTABILIDAD','INFORMATICA',null);
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('13','1','3',to_date('20/08/18','DD/MM/YY'),to_timestamp('20/08/18 18:15:00,000000000','DD/MM/YY HH24:MI:SSXFF'),'1','10000','NJ','GRINGUITOS','TELETUBBIES',null);
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('14','4','1',to_date('20/08/18','DD/MM/YY'),to_timestamp('20/08/18 18:15:00,000000000','DD/MM/YY HH24:MI:SSXFF'),'1','35000','J ','CACHORROS','GRINGUITOS','106');
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('15','7','5',to_date('20/08/18','DD/MM/YY'),to_timestamp('20/08/18 18:20:03,000000000','DD/MM/YY HH24:MI:SSXFF'),'3','50000','J ','STOLICHVAYA','DEVASTADORES','106');
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('16','6','8',to_date('21/08/18','DD/MM/YY'),to_timestamp('21/08/18 18:20:03,000000000','DD/MM/YY HH24:MI:SSXFF'),'3','50000','J ','DON JUAN FC','OLIMPIA','108');
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('17','11','9',to_date('21/08/18','DD/MM/YY'),to_timestamp('21/08/18 18:16:00,000000000','DD/MM/YY HH24:MI:SSXFF'),'2','40000','J ','CONTABILIDAD','LOGISTICA','108');
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('18','10','12',to_date('22/08/18','DD/MM/YY'),to_timestamp('22/08/18 18:16:00,000000000','DD/MM/YY HH24:MI:SSXFF'),'2','5000','NJ','BODEGA','INFORMATICA',null);
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('19','10','3',to_date('23/08/18','DD/MM/YY'),to_timestamp('23/08/18 18:15:00,000000000','DD/MM/YY HH24:MI:SSXFF'),'1','15000','NJ','BODEGA','TELETUBBIES',null);
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('20','11','4',to_date('23/08/18','DD/MM/YY'),to_timestamp('23/08/18 18:15:00,000000000','DD/MM/YY HH24:MI:SSXFF'),'1','15000','J ','CONTABILIDAD','CACHORROS','117');
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('21','8','5',to_date('23/08/18','DD/MM/YY'),to_timestamp('23/08/18 18:20:03,000000000','DD/MM/YY HH24:MI:SSXFF'),'3','50000','J ','OLIMPIA','DEVASTADORES','117');
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('22','6','2',to_date('24/08/18','DD/MM/YY'),to_timestamp('24/08/18 18:20:03,000000000','DD/MM/YY HH24:MI:SSXFF'),'3','40000','J ','DON JUAN FC','PINGUINOS','119');
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('23','12','9',to_date('24/08/18','DD/MM/YY'),to_timestamp('24/08/18 18:16:00,000000000','DD/MM/YY HH24:MI:SSXFF'),'2','8000','NJ','INFORMATICA','LOGISTICA',null);
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('24','1','12',to_date('24/08/18','DD/MM/YY'),to_timestamp('24/08/18 18:16:00,000000000','DD/MM/YY HH24:MI:SSXFF'),'2','10000','NJ','GRINGUITOS','INFORMATICA',null);
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('25','6','3',to_date('25/08/18','DD/MM/YY'),to_timestamp('25/08/18 18:15:00,000000000','DD/MM/YY HH24:MI:SSXFF'),'1','20000','NJ','DON JUAN FC','TELETUBBIES',null);
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('26','11','8',to_date('26/08/18','DD/MM/YY'),to_timestamp('26/08/18 18:15:00,000000000','DD/MM/YY HH24:MI:SSXFF'),'1','35000','J ','CONTABILIDAD','OLIMPIA','120');
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('27','10','5',to_date('27/08/18','DD/MM/YY'),to_timestamp('27/08/18 18:20:03,000000000','DD/MM/YY HH24:MI:SSXFF'),'3','50000','J ','BODEGA','DEVASTADORES','106');
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('28','6','1',to_date('28/08/18','DD/MM/YY'),to_timestamp('28/08/18 18:20:03,000000000','DD/MM/YY HH24:MI:SSXFF'),'3','25000','NJ','DON JUAN FC','GRINGUITOS',null);
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('29','12','4',to_date('28/08/18','DD/MM/YY'),to_timestamp('28/08/18 18:16:00,000000000','DD/MM/YY HH24:MI:SSXFF'),'2','40000','NJ','INFORMATICA','CACHORROS',null);
INSERT INTO programacion (id_programacion,id_equipo_1,id_equipo_2,fecha,hora,id_tarifa,valor_pagado,estado,equipo_1,equipo_2,minutos_jugados) VALUES ('30','9','12',to_date('29/08/18','DD/MM/YY'),to_timestamp('29/08/18 18:16:00,000000000','DD/MM/YY HH24:MI:SSXFF'),'2','40000','J ','LOGISTICA','INFORMATICA','113');

INSERT INTO tarifa (id_tarifa,descripcion,valor,fecha_creacion,fecha_actualizacion,fecha_eliminacion,id_user_creacion,id_user_actualizacion,id_user_eliminacion) VALUES ('1','LOW','35000',to_date('01/08/18','DD/MM/YY'),null,null,'1',null,null);
INSERT INTO tarifa (id_tarifa,descripcion,valor,fecha_creacion,fecha_actualizacion,fecha_eliminacion,id_user_creacion,id_user_actualizacion,id_user_eliminacion) VALUES ('2','MEDIUM','40000',to_date('01/08/18','DD/MM/YY'),null,null,'1',null,null);
INSERT INTO tarifa (id_tarifa,descripcion,valor,fecha_creacion,fecha_actualizacion,fecha_eliminacion,id_user_creacion,id_user_actualizacion,id_user_eliminacion) VALUES ('3','HIGH','50000',to_date('01/08/18','DD/MM/YY'),null,null,'1',null,null);

INSERT INTO tipo_evento (descripcion,relevante,id_tipo_evento) VALUES ('GOL','Y','GL');
INSERT INTO tipo_evento (descripcion,relevante,id_tipo_evento) VALUES ('FOUL','Y','FO');
INSERT INTO tipo_evento (descripcion,relevante,id_tipo_evento) VALUES ('OFF SIDE','N','OF');
INSERT INTO tipo_evento (descripcion,relevante,id_tipo_evento) VALUES ('LATERAL','N','LA');
INSERT INTO tipo_evento (descripcion,relevante,id_tipo_evento) VALUES ('EXPULSION','Y','EX');
INSERT INTO tipo_evento (descripcion,relevante,id_tipo_evento) VALUES ('AMONESTACION','Y','AM');

INSERT INTO usuario (id_user,username,password,fecha_creacion,fecha_bloqueo,nombre,apellido) VALUES ('1','JVALENZUELA','1',to_date('13/11/17','DD/MM/YY'),null,'JUAN','VALENZUELA');
INSERT INTO usuario (id_user,username,password,fecha_creacion,fecha_bloqueo,nombre,apellido) VALUES ('2','MCLARO','1',to_date('13/11/17','DD/MM/YY'),null,'MIGUEL','CLARO');
INSERT INTO usuario (id_user,username,password,fecha_creacion,fecha_bloqueo,nombre,apellido) VALUES ('4','PLORCA','1',to_date('25/07/18','DD/MM/YY'),null,'PABLO','LORCA');
INSERT INTO usuario (id_user,username,password,fecha_creacion,fecha_bloqueo,nombre,apellido) VALUES ('3','CURBINA','1',to_date('22/08/18','DD/MM/YY'),null,'CAROL','URBINA');

-- ALTERAMOS DE LAS TABLAS, INDICANDO LAS PRIMARY Y FOREING KEYS CON SUS RESPECTIVAS RELACIONES
-- Y SE DEFINEN LOS CAMPOS QUE SERAN NULO O NO NULOS

ALTER TABLE "comuna" ADD CONSTRAINT "comuna_pk" PRIMARY KEY ("id");
ALTER TABLE "comuna" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "comuna" ALTER COLUMN "nombre" SET NOT NULL;

ALTER TABLE "jugador_equipo" ADD CONSTRAINT "jugador_equipo_pk" PRIMARY KEY ("id_jugador_equipo");
ALTER TABLE "jugador_equipo" ALTER COLUMN "rut_jugador" SET NOT NULL;
ALTER TABLE "jugador_equipo" ALTER COLUMN "id_equipo" SET NOT NULL;
ALTER TABLE "jugador_equipo" ALTER COLUMN "camiseta" SET NOT NULL;
ALTER TABLE "jugador_equipo" ALTER COLUMN "fecha_incorporacion" SET NOT NULL;
ALTER TABLE "jugador_equipo" ALTER COLUMN "id_jugador_equipo" SET NOT NULL;

ALTER TABLE "tarifa" ADD CONSTRAINT "tarifa_pk" PRIMARY KEY ("id_tarifa");
ALTER TABLE "tarifa" ALTER COLUMN "id_user_creacion" SET NOT NULL;
ALTER TABLE "tarifa" ALTER COLUMN "fecha_creacion" SET NOT NULL;
ALTER TABLE "tarifa" ALTER COLUMN "valor" SET NOT NULL;
ALTER TABLE "tarifa" ALTER COLUMN "descripcion" SET NOT NULL;
ALTER TABLE "tarifa" ALTER COLUMN "id_tarifa" SET NOT NULL;

ALTER TABLE "usuario" ADD PRIMARY KEY ("id_user");
ALTER TABLE "usuario" ALTER COLUMN "password" SET NOT NULL;
ALTER TABLE "usuario" ALTER COLUMN "username" SET NOT NULL;

ALTER TABLE "evento" ADD CONSTRAINT "evento_pk" PRIMARY KEY ("id_evento");
ALTER TABLE "evento" ALTER COLUMN "minuto" SET NOT NULL;
ALTER TABLE "evento" ALTER COLUMN "id_partido" SET NOT NULL;
ALTER TABLE "evento" ALTER COLUMN "id_evento" SET NOT NULL;

ALTER TABLE "tipo_evento" ADD CONSTRAINT "tipo_evento_pk" PRIMARY KEY ("id_tipo_evento");
ALTER TABLE "tipo_evento" ALTER COLUMN "relevante" SET NOT NULL;
ALTER TABLE "tipo_evento" ALTER COLUMN "descripcion" SET NOT NULL;
ALTER TABLE "tipo_evento" ALTER COLUMN "id_tipo_evento" SET NOT NULL;

ALTER TABLE "equipo" ADD CONSTRAINT "equipo_pk" PRIMARY KEY ("id_equipo");
ALTER TABLE "equipo" ALTER COLUMN "id_categoria" SET NOT NULL;
ALTER TABLE "equipo" ALTER COLUMN "fecha_creacion" SET NOT NULL;
ALTER TABLE "equipo" ALTER COLUMN "cantidad_jugador" SET NOT NULL;
ALTER TABLE "equipo" ALTER COLUMN "nombre" SET NOT NULL;
ALTER TABLE "equipo" ALTER COLUMN "id_equipo" SET NOT NULL;

ALTER TABLE "partido" ADD CONSTRAINT "partido_pk" PRIMARY KEY ("id_partido");
ALTER TABLE "partido" ALTER COLUMN "equipo_visita" SET NOT NULL;
ALTER TABLE "partido" ALTER COLUMN "id_tarifa" SET NOT NULL;
ALTER TABLE "partido" ALTER COLUMN "id_user" SET NOT NULL;
ALTER TABLE "partido" ALTER COLUMN "id_equipo_visita" SET NOT NULL;
ALTER TABLE "partido" ALTER COLUMN "id_equipo_local" SET NOT NULL;
ALTER TABLE "partido" ALTER COLUMN "goles_visita" SET NOT NULL;
ALTER TABLE "partido" ALTER COLUMN "goles_local" SET NOT NULL;
ALTER TABLE "partido" ALTER COLUMN "equipo_local" SET NOT NULL;
ALTER TABLE "partido" ALTER COLUMN "id_cancha" SET NOT NULL;
ALTER TABLE "partido" ALTER COLUMN "inicio" SET NOT NULL;
ALTER TABLE "partido" ALTER COLUMN "fecha" SET NOT NULL;
ALTER TABLE "partido" ALTER COLUMN "id_programacion" SET NOT NULL;
ALTER TABLE "partido" ALTER COLUMN "id_partido" SET NOT NULL;

ALTER TABLE "cancha" ADD CONSTRAINT "cancha_pk" PRIMARY KEY ("id_cancha");
ALTER TABLE "cancha" ALTER COLUMN "nombre" SET NOT NULL;
ALTER TABLE "cancha" ALTER COLUMN "id_cancha" SET NOT NULL;

ALTER TABLE "categoria" ADD CONSTRAINT "categoria_pk" PRIMARY KEY ("id_categoria");
ALTER TABLE "categoria" ALTER COLUMN "edad_maxima" SET NOT NULL;
ALTER TABLE "categoria" ALTER COLUMN "edad_minima" SET NOT NULL;
ALTER TABLE "categoria" ALTER COLUMN "nombre" SET NOT NULL;
ALTER TABLE "categoria" ALTER COLUMN "id_categoria" SET NOT NULL;

ALTER TABLE "programacion" ADD CONSTRAINT "programacion_pk" PRIMARY KEY ("id_programacion");
ALTER TABLE "programacion" ALTER COLUMN "estado" SET NOT NULL;
ALTER TABLE "programacion" ALTER COLUMN "valor_pagado" SET NOT NULL;
ALTER TABLE "programacion" ALTER COLUMN "id_tarifa" SET NOT NULL;
ALTER TABLE "programacion" ALTER COLUMN "hora" SET NOT NULL;
ALTER TABLE "programacion" ALTER COLUMN "fecha" SET NOT NULL;
ALTER TABLE "programacion" ALTER COLUMN "id_equipo_2" SET NOT NULL;
ALTER TABLE "programacion" ALTER COLUMN "id_equipo_1" SET NOT NULL;
ALTER TABLE "programacion" ALTER COLUMN "id_programacion" SET NOT NULL;

ALTER TABLE "jugador" ADD CONSTRAINT "jugador_pk" PRIMARY KEY ("rut");
ALTER TABLE "jugador" ALTER COLUMN "apellido" SET NOT NULL;
ALTER TABLE "jugador" ALTER COLUMN "nombre" SET NOT NULL;
ALTER TABLE "jugador" ALTER COLUMN "dv" SET NOT NULL;
ALTER TABLE "jugador" ALTER COLUMN "rut" SET NOT NULL;

ALTER TABLE "equipo" ADD CONSTRAINT "equipo_categoria_fk" FOREIGN KEY ("id_categoria") REFERENCES "categoria" ("id_categoria");

ALTER TABLE "evento" ADD CONSTRAINT "evento_jugador_fk" FOREIGN KEY ("rut_jugador") REFERENCES "jugador" ("rut");
ALTER TABLE "evento" ADD CONSTRAINT "evento_partido_fk" FOREIGN KEY ("id_partido") REFERENCES "partido" ("id_partido");
ALTER TABLE "evento" ADD CONSTRAINT "evento_tipo_evento_fk" FOREIGN KEY ("id_tipo_evento") REFERENCES "tipo_evento" ("id_tipo_evento");

ALTER TABLE "jugador_equipo" ADD CONSTRAINT "jugador_equipo_equipo_fk" FOREIGN KEY ("id_equipo") REFERENCES "equipo" ("id_equipo");
ALTER TABLE "jugador_equipo" ADD CONSTRAINT "jugador_equipo_jugador_fk" FOREIGN KEY ("rut_jugador") REFERENCES "jugador" ("rut");

ALTER TABLE "partido" ADD CONSTRAINT "partido_cancha_fk" FOREIGN KEY ("id_cancha") REFERENCES "cancha" ("id_cancha");
ALTER TABLE "partido" ADD CONSTRAINT "partido_equipo_fk" FOREIGN KEY ("id_equipo_local") REFERENCES "equipo" ("id_equipo");
ALTER TABLE "partido" ADD CONSTRAINT "partido_equipo_fkv1" FOREIGN KEY ("id_equipo_visita") REFERENCES "equipo" ("id_equipo");
ALTER TABLE "partido" ADD CONSTRAINT "partido_programacion_fk" FOREIGN KEY ("id_programacion") REFERENCES "programacion" ("id_programacion");
ALTER TABLE "partido" ADD CONSTRAINT "partido_usuario_fk" FOREIGN KEY ("id_user") REFERENCES "usuario" ("id_user");

ALTER TABLE "programacion" ADD CONSTRAINT "programacion_equipo_1_fk" FOREIGN KEY ("id_equipo_1") REFERENCES "equipo" ("id_equipo");
ALTER TABLE "programacion" ADD CONSTRAINT "programacion_equipo_2_fk" FOREIGN KEY ("id_equipo_2") REFERENCES "equipo" ("id_equipo");
ALTER TABLE "programacion" ADD CONSTRAINT "programacion_tarifa_fk" FOREIGN KEY ("id_tarifa") REFERENCES "tarifa" ("id_tarifa");

ALTER TABLE "tarifa" ADD CONSTRAINT "tarifa_usuario_crea_fk" FOREIGN KEY ("id_user_eliminacion") REFERENCES "usuario" ("id_user");
